services:
  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: auth_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_DB:-auth_app}
      POSTGRES_USER: ${DATABASE_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_SCHEMA: ${DATABASE_SCHEMA:-public}
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - auth_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  auth_network:
    driver: bridge